module.exports = {
  maths: {
    algebra: [
      { q: "Solve: 3x + 7 = 22", options: ["x = 3", "x = 5", "x = 7", "x = 4"], answer: 1, difficulty: 1 },
      { q: "Expand: 2(x + 4)", options: ["2x + 4", "2x + 8", "x + 8", "2x + 6"], answer: 1, difficulty: 1 },
      { q: "Solve: 5x - 3 = 2x + 9", options: ["x = 2", "x = 4", "x = 6", "x = 3"], answer: 1, difficulty: 2 },
      { q: "Factorise: x\u00b2 + 5x + 6", options: ["(x+1)(x+6)", "(x+2)(x+3)", "(x+3)(x+3)", "(x+1)(x+5)"], answer: 1, difficulty: 2 },
      { q: "Simplify: 3a + 2b - a + 4b", options: ["2a + 6b", "4a + 6b", "2a + 2b", "3a + 6b"], answer: 0, difficulty: 1 },
      { q: "Solve: 2(x - 3) = x + 4", options: ["x = 10", "x = 7", "x = 5", "x = 8"], answer: 0, difficulty: 2 },
      { q: "What is the value of x if x/4 + 3 = 7?", options: ["12", "16", "20", "8"], answer: 1, difficulty: 1 },
      { q: "Expand and simplify: (x + 3)(x + 2)", options: ["x\u00b2 + 5x + 6", "x\u00b2 + 6x + 5", "x\u00b2 + 5x + 5", "x\u00b2 + 6x + 6"], answer: 0, difficulty: 2 },
    ],
    bearings: [
      { q: "A bearing is always measured from which direction?", options: ["South", "East", "North", "West"], answer: 2, difficulty: 1 },
      { q: "Bearings are measured in which direction?", options: ["Anticlockwise", "Clockwise", "Both ways", "Depends on question"], answer: 1, difficulty: 1 },
      { q: "What is the bearing of East?", options: ["000\u00b0", "090\u00b0", "180\u00b0", "270\u00b0"], answer: 1, difficulty: 1 },
      { q: "What is the bearing of South-West?", options: ["135\u00b0", "225\u00b0", "315\u00b0", "045\u00b0"], answer: 1, difficulty: 1 },
      { q: "If the bearing of B from A is 070\u00b0, what is the bearing of A from B?", options: ["250\u00b0", "110\u00b0", "290\u00b0", "070\u00b0"], answer: 0, difficulty: 2 },
      { q: "A ship sails on a bearing of 135\u00b0. Which direction is it heading?", options: ["North-East", "South-East", "South-West", "North-West"], answer: 1, difficulty: 1 },
      { q: "The bearing of X from Y is 300\u00b0. What is the bearing of Y from X?", options: ["120\u00b0", "060\u00b0", "240\u00b0", "300\u00b0"], answer: 0, difficulty: 2 },
      { q: "A bearing must always be written as:", options: ["1 digit", "2 digits", "3 digits", "4 digits"], answer: 2, difficulty: 1 },
      { q: "What is the bearing of North?", options: ["360\u00b0", "000\u00b0", "090\u00b0", "180\u00b0"], answer: 1, difficulty: 1 },
      { q: "If bearing of P from Q is 045\u00b0, P is in which direction from Q?", options: ["North-East", "South-East", "North-West", "South-West"], answer: 0, difficulty: 2 },
    ],
    compound_shapes: [
      { q: "A compound shape is made of a 6\u00d74 rectangle and a 3\u00d74 rectangle. Total area?", options: ["36 cm\u00b2", "30 cm\u00b2", "24 cm\u00b2", "42 cm\u00b2"], answer: 0, difficulty: 1 },
      { q: "An L-shape has outer dimensions 10\u00d78 with a 4\u00d73 piece cut out. Area?", options: ["68 cm\u00b2", "80 cm\u00b2", "76 cm\u00b2", "56 cm\u00b2"], answer: 0, difficulty: 2 },
      { q: "A T-shape is made of two rectangles: 8\u00d72 on top and 3\u00d76 below. Total area?", options: ["34 cm\u00b2", "30 cm\u00b2", "36 cm\u00b2", "28 cm\u00b2"], answer: 0, difficulty: 1 },
      { q: "To find perimeter of a compound shape, you:", options: ["Add all inner sides", "Add all outer sides", "Multiply length \u00d7 width", "Add areas together"], answer: 1, difficulty: 1 },
      { q: "A rectangle 12\u00d75 has a 4\u00d73 rectangle removed from corner. Perimeter?", options: ["34 cm", "48 cm", "40 cm", "44 cm"], answer: 2, difficulty: 2 },
      { q: "Two squares of side 5cm overlap by 2cm. Combined area (no overlap counted twice)?", options: ["46 cm\u00b2", "50 cm\u00b2", "48 cm\u00b2", "44 cm\u00b2"], answer: 0, difficulty: 2 },
      { q: "A shape is a 10\u00d76 rectangle with a semicircle (diameter 6) on one end. Area? (\u03c0=3.14)", options: ["74.13 cm\u00b2", "60 cm\u00b2", "88.26 cm\u00b2", "81.42 cm\u00b2"], answer: 0, difficulty: 2 },
      { q: "Compound shape: rectangle 8\u00d75 joined to triangle base 8, height 3. Total area?", options: ["52 cm\u00b2", "55 cm\u00b2", "64 cm\u00b2", "40 cm\u00b2"], answer: 0, difficulty: 1 },
    ],
    circles: [
      { q: "What is the circumference of a circle with radius 7cm? (\u03c0 = 22/7)", options: ["44 cm", "22 cm", "154 cm", "38 cm"], answer: 0, difficulty: 1 },
      { q: "Find the area of a circle with radius 5cm (\u03c0 = 3.14)", options: ["78.5 cm\u00b2", "31.4 cm\u00b2", "15.7 cm\u00b2", "25 cm\u00b2"], answer: 0, difficulty: 1 },
      { q: "Diameter of a circle is 12cm. What is the circumference? (\u03c0 = 3.14)", options: ["37.68 cm", "18.84 cm", "113.04 cm", "75.36 cm"], answer: 0, difficulty: 1 },
      { q: "A semicircle has diameter 10cm. What is its perimeter? (\u03c0 = 3.14)", options: ["25.7 cm", "15.7 cm", "31.4 cm", "20.7 cm"], answer: 0, difficulty: 2 },
      { q: "Area of a circle is 154 cm\u00b2. What is the radius? (\u03c0 = 22/7)", options: ["7 cm", "14 cm", "49 cm", "21 cm"], answer: 0, difficulty: 2 },
      { q: "A quarter circle has radius 8cm. What is its area? (\u03c0 = 3.14)", options: ["50.24 cm\u00b2", "200.96 cm\u00b2", "25.12 cm\u00b2", "100.48 cm\u00b2"], answer: 0, difficulty: 2 },
      { q: "The formula for circumference is:", options: ["\u03c0r\u00b2", "2\u03c0r", "\u03c0d\u00b2", "2\u03c0d"], answer: 1, difficulty: 1 },
      { q: "A circle has circumference 31.4cm. What is the diameter? (\u03c0 = 3.14)", options: ["10 cm", "5 cm", "20 cm", "15 cm"], answer: 0, difficulty: 2 },
    ],
    angles: [
      { q: "What is the sum of interior angles of a triangle?", options: ["90\u00b0", "180\u00b0", "360\u00b0", "270\u00b0"], answer: 1, difficulty: 1 },
      { q: "Sum of interior angles of a hexagon (6 sides)?", options: ["540\u00b0", "720\u00b0", "900\u00b0", "360\u00b0"], answer: 1, difficulty: 1 },
      { q: "Each exterior angle of a regular pentagon?", options: ["108\u00b0", "72\u00b0", "60\u00b0", "90\u00b0"], answer: 1, difficulty: 2 },
      { q: "Exterior angles of any polygon always sum to:", options: ["180\u00b0", "360\u00b0", "540\u00b0", "720\u00b0"], answer: 1, difficulty: 1 },
      { q: "Each interior angle of a regular octagon?", options: ["135\u00b0", "120\u00b0", "140\u00b0", "150\u00b0"], answer: 0, difficulty: 2 },
      { q: "A regular polygon has exterior angle 40\u00b0. How many sides?", options: ["8", "9", "10", "12"], answer: 1, difficulty: 2 },
      { q: "Formula for sum of interior angles of n-sided polygon?", options: ["180n", "(n-2)\u00d7180", "(n+2)\u00d7180", "360\u00f7n"], answer: 1, difficulty: 1 },
      { q: "Interior + Exterior angle at any vertex equals:", options: ["90\u00b0", "180\u00b0", "360\u00b0", "270\u00b0"], answer: 1, difficulty: 1 },
      { q: "Sum of interior angles of a quadrilateral?", options: ["180\u00b0", "270\u00b0", "360\u00b0", "540\u00b0"], answer: 2, difficulty: 1 },
      { q: "A regular polygon has interior angle 150\u00b0. How many sides?", options: ["10", "12", "8", "15"], answer: 1, difficulty: 2 },
    ],
    probability: [
      { q: "A fair dice is rolled. P(getting 6)?", options: ["1/2", "1/6", "1/3", "6/6"], answer: 1, difficulty: 1 },
      { q: "A coin is flipped twice. P(two heads)?", options: ["1/2", "1/4", "1/3", "3/4"], answer: 1, difficulty: 1 },
      { q: "Bag has 3 red, 5 blue, 2 green balls. P(blue)?", options: ["1/2", "5/10", "3/10", "2/10"], answer: 1, difficulty: 1 },
      { q: "P(event) + P(not event) = ?", options: ["0", "0.5", "1", "2"], answer: 2, difficulty: 1 },
      { q: "P(impossible event) = ?", options: ["0", "1", "0.5", "-1"], answer: 0, difficulty: 1 },
      { q: "A spinner has sections: 2 red, 3 blue, 5 green. P(not green)?", options: ["1/2", "5/10", "3/10", "7/10"], answer: 0, difficulty: 2 },
      { q: "Two dice rolled. P(total = 7)?", options: ["1/6", "6/36", "7/36", "1/12"], answer: 1, difficulty: 2 },
      { q: "A card is drawn from 52 cards. P(heart)?", options: ["1/4", "1/13", "1/52", "1/2"], answer: 0, difficulty: 1 },
      { q: "Events A and B are independent. P(A)=0.3, P(B)=0.5. P(A and B)?", options: ["0.8", "0.15", "0.2", "0.35"], answer: 1, difficulty: 2 },
      { q: "Relative frequency of heads in 200 flips is 0.55. How many heads?", options: ["110", "100", "55", "90"], answer: 0, difficulty: 2 },
    ],
    percentages: [
      { q: "What is 25% of 160?", options: ["40", "35", "45", "32"], answer: 0, difficulty: 1 },
      { q: "A shirt costs \u00a340. Sale is 15% off. Sale price?", options: ["\u00a334", "\u00a336", "\u00a332", "\u00a338"], answer: 0, difficulty: 1 },
      { q: "Express 45 out of 60 as a percentage", options: ["70%", "75%", "80%", "65%"], answer: 1, difficulty: 1 },
      { q: "A price increases from \u00a380 to \u00a3100. % increase?", options: ["20%", "25%", "15%", "30%"], answer: 1, difficulty: 2 },
      { q: "After 10% decrease, value is 63. Original value?", options: ["70", "73", "67", "60"], answer: 0, difficulty: 2 },
      { q: "VAT is 20%. Item costs \u00a360 before VAT. Total?", options: ["\u00a372", "\u00a368", "\u00a380", "\u00a370"], answer: 0, difficulty: 1 },
      { q: "A house was \u00a3200,000. Increased by 5% then decreased by 5%. Final price?", options: ["\u00a3200,000", "\u00a3199,500", "\u00a3199,000", "\u00a3201,000"], answer: 1, difficulty: 2 },
      { q: "30% of a number is 45. What is the number?", options: ["135", "150", "120", "180"], answer: 1, difficulty: 2 },
      { q: "\u00a3500 invested at 3% simple interest for 4 years. Total interest?", options: ["\u00a360", "\u00a350", "\u00a345", "\u00a365"], answer: 0, difficulty: 1 },
      { q: "Population grows from 5000 to 6500. % increase?", options: ["25%", "30%", "35%", "20%"], answer: 1, difficulty: 2 },
    ],
  },
  science: {
    forces: [
      { q: "What is the unit of force?", options: ["Joule", "Newton", "Watt", "Pascal"], answer: 1, difficulty: 1 },
      { q: "A 10kg object has weight (g=10 m/s\u00b2):", options: ["10N", "100N", "1000N", "1N"], answer: 1, difficulty: 1 },
      { q: "Which force slows down a moving car?", options: ["Gravity", "Friction", "Thrust", "Upthrust"], answer: 1, difficulty: 1 },
      { q: "F = ma. Force=20N, mass=5kg. Acceleration=?", options: ["100 m/s\u00b2", "4 m/s\u00b2", "25 m/s\u00b2", "15 m/s\u00b2"], answer: 1, difficulty: 1 },
      { q: "An object at rest stays at rest unless a force acts. This is Newton's:", options: ["1st Law", "2nd Law", "3rd Law", "Law of Gravity"], answer: 0, difficulty: 1 },
      { q: "A 2kg ball accelerates at 3 m/s\u00b2. Force applied?", options: ["5N", "6N", "1.5N", "8N"], answer: 1, difficulty: 2 },
      { q: "What happens to friction when surfaces are smoother?", options: ["Increases", "Decreases", "Stays same", "Becomes zero"], answer: 1, difficulty: 1 },
      { q: "A car has driving force 500N and friction 200N. Resultant force?", options: ["700N", "300N", "200N", "500N"], answer: 1, difficulty: 2 },
      { q: "If resultant force on an object is zero, the object:", options: ["Speeds up", "Slows down", "Stays at constant velocity", "Stops immediately"], answer: 2, difficulty: 2 },
      { q: "Weight is measured in:", options: ["kg", "Newtons", "m/s\u00b2", "Joules"], answer: 1, difficulty: 1 },
    ],
    electromagnetism: [
      { q: "What is an electromagnet made of?", options: ["Permanent magnet", "Coil of wire + iron core", "Copper only", "Rubber and wire"], answer: 1, difficulty: 1 },
      { q: "How can you make an electromagnet stronger?", options: ["More coils", "More current", "Add iron core", "All of these"], answer: 3, difficulty: 1 },
      { q: "What device uses an electromagnet to switch a circuit on/off?", options: ["Resistor", "Relay", "Capacitor", "Diode"], answer: 1, difficulty: 2 },
      { q: "A current-carrying wire in a magnetic field experiences a:", options: ["Force", "Voltage", "Resistance", "Charge"], answer: 0, difficulty: 1 },
      { q: "The motor effect is used in:", options: ["Generators", "Electric motors", "Transformers", "Batteries"], answer: 1, difficulty: 1 },
      { q: "Fleming's Left Hand Rule: thumb represents:", options: ["Current", "Field", "Force (motion)", "Voltage"], answer: 2, difficulty: 2 },
      { q: "What happens when you reverse current in an electromagnet?", options: ["Nothing", "It gets weaker", "Poles reverse", "It stops working"], answer: 2, difficulty: 1 },
      { q: "Which material is best for an electromagnet core?", options: ["Copper", "Soft iron", "Steel", "Aluminium"], answer: 1, difficulty: 2 },
      { q: "An electromagnet differs from a permanent magnet because it:", options: ["Is always on", "Can be switched on/off", "Is stronger", "Has no poles"], answer: 1, difficulty: 1 },
      { q: "A solenoid is:", options: ["A type of battery", "A coil of wire", "A permanent magnet", "A circuit breaker"], answer: 1, difficulty: 1 },
    ],
    work_done: [
      { q: "The formula for work done is:", options: ["Force \u00d7 Time", "Force \u00d7 Distance", "Mass \u00d7 Velocity", "Power \u00d7 Time"], answer: 1, difficulty: 1 },
      { q: "What is the unit of work done?", options: ["Newton", "Watt", "Joule", "Pascal"], answer: 2, difficulty: 1 },
      { q: "A force of 50N moves an object 4m. Work done?", options: ["200J", "12.5J", "54J", "100J"], answer: 0, difficulty: 1 },
      { q: "If you push a wall but it doesn't move, work done is:", options: ["50J", "100J", "0J", "Depends on force"], answer: 2, difficulty: 1 },
      { q: "A crane lifts 200kg by 5m (g=10). Work done against gravity?", options: ["1000J", "10000J", "40J", "2000J"], answer: 1, difficulty: 2 },
      { q: "Work done = 600J, distance = 20m. What force was applied?", options: ["30N", "12000N", "580N", "620N"], answer: 0, difficulty: 2 },
      { q: "Power = Work done \u00f7 Time. 500J in 10s = ?", options: ["50W", "5000W", "5W", "500W"], answer: 0, difficulty: 1 },
      { q: "A person does 1500J of work in 30 seconds. Their power is:", options: ["50W", "45000W", "500W", "30W"], answer: 0, difficulty: 2 },
      { q: "If no friction, work done against friction is:", options: ["Maximum", "Zero", "Infinite", "Same as gravity"], answer: 1, difficulty: 1 },
      { q: "Which scenario has the most work done? (same force)", options: ["Moving 2m", "Moving 5m", "Moving 10m", "Not moving"], answer: 2, difficulty: 1 },
    ],
    periodic_table: [
      { q: "Who created the first widely accepted periodic table?", options: ["Dalton", "Mendeleev", "Newton", "Bohr"], answer: 1, difficulty: 1 },
      { q: "Elements in the same GROUP have the same number of:", options: ["Protons", "Electron shells", "Outer electrons", "Neutrons"], answer: 2, difficulty: 1 },
      { q: "Elements in the same PERIOD have the same number of:", options: ["Outer electrons", "Electron shells", "Protons", "Neutrons"], answer: 1, difficulty: 1 },
      { q: "Group 1 elements are called:", options: ["Noble gases", "Halogens", "Alkali metals", "Transition metals"], answer: 2, difficulty: 1 },
      { q: "Group 7 elements are called:", options: ["Noble gases", "Halogens", "Alkali metals", "Alkaline earth metals"], answer: 1, difficulty: 1 },
      { q: "Group 0 elements are unreactive because they have:", options: ["No electrons", "Full outer shell", "No protons", "One outer electron"], answer: 1, difficulty: 1 },
      { q: "As you go DOWN Group 1, reactivity:", options: ["Decreases", "Increases", "Stays same", "Becomes zero"], answer: 1, difficulty: 2 },
      { q: "As you go DOWN Group 7, reactivity:", options: ["Decreases", "Increases", "Stays same", "Becomes zero"], answer: 0, difficulty: 2 },
      { q: "What is the atomic number of an element?", options: ["Number of neutrons", "Number of protons", "Mass number", "Number of shells"], answer: 1, difficulty: 1 },
      { q: "Which is a noble gas?", options: ["Sodium", "Chlorine", "Neon", "Potassium"], answer: 2, difficulty: 1 },
      { q: "Metals are found on which side of the periodic table?", options: ["Right", "Left", "Centre only", "Bottom only"], answer: 1, difficulty: 1 },
      { q: "What is the electronic structure of Sodium (atomic number 11)?", options: ["2,8,1", "2,8,2", "2,1,8", "8,2,1"], answer: 0, difficulty: 2 },
    ],
    reactions: [
      { q: "What gas is produced when acid reacts with metal?", options: ["Oxygen", "Carbon dioxide", "Hydrogen", "Nitrogen"], answer: 2, difficulty: 1 },
      { q: "Acid + Base \u2192 ?", options: ["Salt + Hydrogen", "Salt + Water", "Salt + CO\u2082", "Metal + Water"], answer: 1, difficulty: 1 },
      { q: "What is the pH of a neutral substance?", options: ["0", "7", "14", "1"], answer: 1, difficulty: 1 },
      { q: "Iron + Oxygen \u2192 Iron Oxide is:", options: ["Reduction", "Oxidation", "Neutralisation", "Displacement"], answer: 1, difficulty: 1 },
      { q: "Which gas turns limewater milky?", options: ["Oxygen", "Hydrogen", "Carbon dioxide", "Nitrogen"], answer: 2, difficulty: 1 },
      { q: "In a chemical reaction, mass is:", options: ["Created", "Destroyed", "Conserved", "Doubled"], answer: 2, difficulty: 1 },
      { q: "Zinc + Copper Sulphate \u2192 Zinc Sulphate + Copper. This is:", options: ["Decomposition", "Displacement", "Neutralisation", "Combustion"], answer: 1, difficulty: 2 },
      { q: "What speeds up a reaction without being used up?", options: ["Reactant", "Product", "Catalyst", "Solvent"], answer: 2, difficulty: 2 },
    ],
  },
};
