module.exports = {
  maths: {
    addition: [
      { q: "What is 34 + 27?", options: ["51", "61", "71", "57"], answer: 1, difficulty: 1 },
      { q: "What is 56 + 38?", options: ["84", "94", "88", "92"], answer: 1, difficulty: 1 },
      { q: "What is 125 + 67?", options: ["182", "192", "202", "188"], answer: 1, difficulty: 2 },
      { q: "What is 248 + 156?", options: ["394", "404", "384", "414"], answer: 1, difficulty: 2 },
      { q: "What is 45 + 29 + 11?", options: ["75", "85", "95", "80"], answer: 1, difficulty: 2 },
      { q: "What is 99 + 47?", options: ["136", "146", "156", "142"], answer: 1, difficulty: 1 },
      { q: "What is 300 + 450?", options: ["700", "750", "650", "800"], answer: 1, difficulty: 1 },
      { q: "What is 167 + 233?", options: ["390", "400", "410", "380"], answer: 1, difficulty: 2 },
      { q: "What is 78 + 45?", options: ["113", "123", "133", "118"], answer: 1, difficulty: 1 },
      { q: "What is 199 + 56?", options: ["245", "255", "265", "250"], answer: 1, difficulty: 2 },
    ],
    subtraction: [
      { q: "What is 83 - 47?", options: ["46", "36", "26", "34"], answer: 1, difficulty: 1 },
      { q: "What is 100 - 37?", options: ["73", "63", "67", "57"], answer: 1, difficulty: 1 },
      { q: "What is 256 - 89?", options: ["177", "167", "157", "187"], answer: 1, difficulty: 2 },
      { q: "What is 500 - 236?", options: ["274", "264", "254", "284"], answer: 1, difficulty: 2 },
      { q: "What is 72 - 28?", options: ["54", "44", "34", "48"], answer: 1, difficulty: 1 },
      { q: "What is 145 - 67?", options: ["88", "78", "68", "82"], answer: 1, difficulty: 2 },
      { q: "What is 200 - 85?", options: ["125", "115", "105", "120"], answer: 1, difficulty: 1 },
      { q: "What is 431 - 178?", options: ["263", "253", "243", "257"], answer: 1, difficulty: 2 },
      { q: "What is 90 - 56?", options: ["44", "34", "24", "38"], answer: 1, difficulty: 1 },
      { q: "What is 600 - 347?", options: ["263", "253", "243", "257"], answer: 1, difficulty: 2 },
    ],
    multiplication: [
      { q: "What is 6 × 7?", options: ["36", "42", "48", "35"], answer: 1, difficulty: 1 },
      { q: "What is 8 × 4?", options: ["28", "32", "36", "24"], answer: 1, difficulty: 1 },
      { q: "What is 9 × 6?", options: ["48", "54", "56", "63"], answer: 1, difficulty: 1 },
      { q: "What is 7 × 8?", options: ["54", "56", "48", "63"], answer: 1, difficulty: 1 },
      { q: "What is 12 × 5?", options: ["50", "60", "55", "65"], answer: 1, difficulty: 2 },
      { q: "What is 11 × 7?", options: ["67", "77", "87", "70"], answer: 1, difficulty: 2 },
      { q: "What is 3 × 9?", options: ["24", "27", "21", "30"], answer: 1, difficulty: 1 },
      { q: "What is 4 × 12?", options: ["44", "48", "52", "46"], answer: 1, difficulty: 2 },
      { q: "What is 5 × 5?", options: ["20", "25", "30", "15"], answer: 1, difficulty: 1 },
      { q: "What is 6 × 8?", options: ["42", "48", "54", "44"], answer: 1, difficulty: 1 },
    ],
    division: [
      { q: "What is 36 ÷ 6?", options: ["5", "6", "7", "8"], answer: 1, difficulty: 1 },
      { q: "What is 48 ÷ 8?", options: ["5", "6", "7", "8"], answer: 1, difficulty: 1 },
      { q: "What is 72 ÷ 9?", options: ["7", "8", "9", "6"], answer: 1, difficulty: 1 },
      { q: "What is 56 ÷ 7?", options: ["7", "8", "9", "6"], answer: 1, difficulty: 1 },
      { q: "What is 84 ÷ 12?", options: ["6", "7", "8", "9"], answer: 1, difficulty: 2 },
      { q: "What is 96 ÷ 8?", options: ["11", "12", "13", "10"], answer: 1, difficulty: 2 },
      { q: "What is 45 ÷ 5?", options: ["8", "9", "10", "7"], answer: 1, difficulty: 1 },
      { q: "What is 63 ÷ 9?", options: ["6", "7", "8", "9"], answer: 1, difficulty: 1 },
      { q: "What is 110 ÷ 11?", options: ["9", "10", "11", "12"], answer: 1, difficulty: 2 },
      { q: "What is 144 ÷ 12?", options: ["11", "12", "13", "14"], answer: 1, difficulty: 2 },
    ],
  },
  english: {
    spelling: [
      { q: "Which is spelled correctly?", options: ["becuz", "because", "becouse", "becuase"], answer: 1, difficulty: 1 },
      { q: "Which is spelled correctly?", options: ["diffrent", "diferent", "different", "differant"], answer: 2, difficulty: 1 },
      { q: "Which is spelled correctly?", options: ["beautful", "beautiful", "beutiful", "beautyful"], answer: 1, difficulty: 2 },
      { q: "Which is spelled correctly?", options: ["wednesday", "wendsday", "wensday", "Wednesday"], answer: 3, difficulty: 1 },
      { q: "Which is spelled correctly?", options: ["febuary", "February", "Febrary", "Feburary"], answer: 1, difficulty: 2 },
      { q: "Which is spelled correctly?", options: ["separete", "seperate", "separate", "seperite"], answer: 2, difficulty: 2 },
      { q: "Which is spelled correctly?", options: ["knowlege", "knowledge", "knolege", "knowladge"], answer: 1, difficulty: 2 },
      { q: "Which is spelled correctly?", options: ["frend", "freind", "friend", "frind"], answer: 2, difficulty: 1 },
      { q: "Which is spelled correctly?", options: ["togeather", "togather", "together", "togethar"], answer: 2, difficulty: 1 },
      { q: "Which is spelled correctly?", options: ["believe", "beleive", "belive", "beleave"], answer: 0, difficulty: 2 },
    ],
    punctuation: [
      { q: "Which sentence uses a comma correctly?", options: ["I like apples oranges and bananas.", "I like apples, oranges and bananas.", "I like, apples oranges and bananas.", "I like apples oranges, and bananas."], answer: 1, difficulty: 1 },
      { q: "Which sentence has correct punctuation?", options: ["whats your name", "What's your name?", "Whats your name?", "What's your name"], answer: 1, difficulty: 1 },
      { q: "Where does the apostrophe go? 'The dogs bone'", options: ["The dog's bone", "The dogs' bone", "The do'gs bone", "The dogs bone'"], answer: 0, difficulty: 1 },
      { q: "Which needs a question mark?", options: ["I like cake", "She went home", "Where is my bag", "He ran fast"], answer: 2, difficulty: 1 },
      { q: "Which uses an exclamation mark correctly?", options: ["I went to school!", "What a beautiful day!", "The cat sat down!", "I like reading!"], answer: 1, difficulty: 1 },
      { q: "Which sentence uses speech marks correctly?", options: ["\"Hello,\" said Tom.", "Hello, said Tom.", "\"Hello, said Tom.\"", "Hello\", said Tom.\""], answer: 0, difficulty: 2 },
      { q: "Which is correct?", options: ["its raining", "it's raining", "its' raining", "i'ts raining"], answer: 1, difficulty: 2 },
      { q: "Where should the full stop go? 'The cat sat on the mat'", options: ["The cat sat on the mat.", "The cat sat. on the mat", ".The cat sat on the mat", "The cat sat on. the mat"], answer: 0, difficulty: 1 },
      { q: "Which shows a list with correct commas?", options: ["I need eggs milk and butter.", "I need eggs, milk, and butter.", "I need, eggs milk and butter.", "I need eggs milk, and butter."], answer: 1, difficulty: 2 },
      { q: "The children's toys means:", options: ["Toys belonging to one child", "Toys belonging to more than one child", "The children are toys", "No meaning"], answer: 1, difficulty: 2 },
    ],
    conjunction: [
      { q: "Join: 'I was tired. I went to bed.' Which conjunction?", options: ["but", "so", "or", "because"], answer: 1, difficulty: 1 },
      { q: "Which conjunction fits? 'I like tea ___ I don't like coffee.'", options: ["and", "but", "so", "because"], answer: 1, difficulty: 1 },
      { q: "Which is a conjunction?", options: ["quickly", "and", "happy", "run"], answer: 1, difficulty: 1 },
      { q: "'I stayed inside ___ it was raining.' Which word fits?", options: ["but", "or", "because", "and"], answer: 2, difficulty: 1 },
      { q: "'Would you like cake ___ biscuits?' Which conjunction?", options: ["and", "but", "or", "so"], answer: 2, difficulty: 1 },
      { q: "'___ it was cold, she wore a coat.' Which word?", options: ["But", "Because", "Or", "And"], answer: 1, difficulty: 2 },
      { q: "Which sentence uses 'although' correctly?", options: ["Although he ran fast, he missed the bus.", "He ran although fast.", "Although, he ran fast he missed.", "He although ran fast."], answer: 0, difficulty: 2 },
      { q: "'I will go ___ you come with me.' Which fits?", options: ["but", "if", "or", "so"], answer: 1, difficulty: 2 },
      { q: "Which is a subordinating conjunction?", options: ["and", "but", "when", "or"], answer: 2, difficulty: 2 },
      { q: "'She sang ___ danced at the party.' Which conjunction?", options: ["but", "and", "because", "if"], answer: 1, difficulty: 1 },
    ],
  },
  science: {
    general: [
      { q: "Which part of a plant makes food?", options: ["Root", "Stem", "Leaf", "Flower"], answer: 2, difficulty: 1 },
      { q: "What do plants need to grow?", options: ["Water, light, soil", "Just water", "Just light", "Only soil"], answer: 0, difficulty: 1 },
      { q: "Which material is magnetic?", options: ["Wood", "Plastic", "Iron", "Glass"], answer: 2, difficulty: 1 },
      { q: "What is the source of light during the day?", options: ["Moon", "Stars", "Sun", "Lamp"], answer: 2, difficulty: 1 },
      { q: "Which is a natural source of light?", options: ["Torch", "Lamp", "Sun", "TV"], answer: 2, difficulty: 1 },
      { q: "Shadows are formed when light is:", options: ["Reflected", "Blocked", "Absorbed", "Bent"], answer: 1, difficulty: 1 },
      { q: "What do animals need to survive?", options: ["Food, water, air", "Only food", "Only water", "Only air"], answer: 0, difficulty: 1 },
      { q: "Which is NOT a type of rock?", options: ["Igneous", "Sedimentary", "Metamorphic", "Magnetic"], answer: 3, difficulty: 2 },
      { q: "Bones and muscles help us to:", options: ["Digest food", "Move", "Breathe", "See"], answer: 1, difficulty: 1 },
      { q: "What does a thermometer measure?", options: ["Weight", "Length", "Temperature", "Time"], answer: 2, difficulty: 1 },
      { q: "Which force pulls things down to Earth?", options: ["Friction", "Magnetism", "Gravity", "Air resistance"], answer: 2, difficulty: 2 },
      { q: "Soil is made up of:", options: ["Only sand", "Tiny bits of rock, dead plants and animals", "Only clay", "Only water"], answer: 1, difficulty: 2 },
      { q: "What is the job of the roots?", options: ["Make food", "Absorb water", "Make seeds", "Attract bees"], answer: 1, difficulty: 1 },
      { q: "Which state of matter has a fixed shape?", options: ["Liquid", "Gas", "Solid", "Vapour"], answer: 2, difficulty: 2 },
      { q: "What happens to water when it freezes?", options: ["It becomes a gas", "It becomes a solid", "It disappears", "It becomes hotter"], answer: 1, difficulty: 1 },
    ],
  },
};
